Arch = [
    "adobe-base-14-fonts",
    "alsa-plugins",
    "amdvlk",
    "android-file-transfer",
    "apt",
    "ast-grep-bin",
    "bind",
    "bitwarden",
    "breeze",
    "breeze-gtk",
    "breeze5",
    "cheese",
    "chromium",
    "code",
    "cronie",
    "dhcpcd",
    "dialog",
    "discover",
    "docker",
    "docker-compose",
    "dolphin",
    "dosfstools",
    "dotnet-host",
    "dotnet-runtime",
    "dotnet-sdk",
    "dxvk-bin",
    "efibootmgr",
    "element-desktop",
    "extundelete",
    "fastfetch",
    "ffmpegthumbnailer",
    "flatpak",
    "frotz-sdl",
    "gamescope",
    "gdb",
    "github-cli",
    "gst-libav",
    "gst-plugin-gtk",
    "gst-plugins-ugly",
    "gstreamer-vaapi",
    "gvfs",
    "gvfs-smb",
    "heaptrack",
    "hunspell-en_gb",
    "inetutils",
    "jpegoptim",
    "jq",
    "kanata-bin",
    "kdenlive",
    "kitty",
    "kondo",
    "kooha",
    "krita",
    "ldproxy",
    "lib32-alsa-lib",
    "lib32-alsa-plugins",
    "lib32-giflib",
    "lib32-gnutls",
    "lib32-gst-plugins-base-libs",
    "lib32-gtk3",
    "lib32-libgcrypt",
    "lib32-libgpg-error",
    "lib32-libjpeg-turbo",
    "lib32-libldap",
    "lib32-libpng",
    "lib32-libpulse",
    "lib32-libva",
    "lib32-libxcomposite",
    "lib32-libxinerama",
    "lib32-libxslt",
    "lib32-mpg123",
    "lib32-ncurses",
    "lib32-ocl-icd",
    "lib32-openal",
    "lib32-sqlite",
    "lib32-v4l-utils",
    "lib32-vulkan-icd-loader",
    "libva-mesa-driver",
    "live-media",
    "lua-format",
    "lutris",
    "mdformat",
    "meld",
    "memtester",
    "mesa-vdpau",
    "mold",
    "mullvad-vpn-bin",
    "nasm",
    "net-tools",
    "network-manager-applet",
    "nfs-utils",
    "nicotine+",
    "nodejs-cz-emoji",
    "openh264",
    "openssl-1.1",
    "otf-aurulent-nerd",
    "otf-codenewroman-nerd",
    "otf-comicshanns-nerd",
    "otf-commit-mono-nerd",
    "otf-droid-nerd",
    "otf-firamono-nerd",
    "otf-geist-mono-nerd",
    "otf-hasklig-nerd",
    "otf-hermit-nerd",
    "otf-monaspace-nerd",
    "otf-opendyslexic-nerd",
    "otf-overpass-nerd",
    "pacutils",
    "perl-class-accessor",
    "perl-log-log4perl",
    "perl-term-shell",
    "pngcheck",
    "progress",
    "python-pipx",
    "python36",
    "qbittorrent",
    "qemu-user-static",
    "qemu-user-static-binfmt",
    "qpwgraph",
    "qt5ct",
    "reflector",
    "rofi-rbw",
    "rsnapshot",
    "rustscan",
    "shfmt",
    "shotcut",
    "spotify-launcher",
    "sqlitebrowser",
    "sshfs",
    "swtpm",
    "sysbench",
    "tectonic",
    "thunar",
    "thunar-archive-plugin",
    "thunar-media-tags-plugin",
    "thunar-volman",
    "trippy",
    "ttf-0xproto-nerd",
    "ttf-3270-nerd",
    "ttf-agave-nerd",
    "ttf-anonymouspro-nerd",
    "ttf-arimo-nerd",
    "ttf-bigblueterminal-nerd",
    "ttf-bitstream-vera-mono-nerd",
    "ttf-cascadia-code-nerd",
    "ttf-cascadia-mono-nerd",
    "ttf-cousine-nerd",
    "ttf-d2coding-nerd",
    "ttf-daddytime-mono-nerd",
    "ttf-dejavu-nerd",
    "ttf-envycoder-nerd",
    "ttf-fantasque-nerd",
    "ttf-go-nerd",
    "ttf-hack-nerd",
    "ttf-heavydata-nerd",
    "ttf-iawriter-nerd",
    "ttf-ibmplex-mono-nerd",
    "ttf-inconsolata-go-nerd",
    "ttf-inconsolata-lgc-nerd",
    "ttf-inconsolata-nerd",
    "ttf-intone-nerd",
    "ttf-iosevka-nerd",
    "ttf-iosevkaterm-nerd",
    "ttf-jetbrains-mono-nerd",
    "ttf-lekton-nerd",
    "ttf-liberation-mono-nerd",
    "ttf-lilex-nerd",
    "ttf-martian-mono-nerd",
    "ttf-meslo-nerd",
    "ttf-monofur-nerd",
    "ttf-monoid-nerd",
    "ttf-mononoki-nerd",
    "ttf-mplus-nerd",
    "ttf-nerd-fonts-symbols-mono",
    "ttf-noto-nerd",
    "ttf-profont-nerd",
    "ttf-proggyclean-nerd",
    "ttf-roboto-mono-nerd",
    "ttf-sharetech-mono-nerd",
    "ttf-sourcecodepro-nerd",
    "ttf-space-mono-nerd",
    "ttf-terminus-nerd",
    "ttf-tinos-nerd",
    "ttf-ubuntu-mono-nerd",
    "ttf-ubuntu-nerd",
    "ttf-victor-mono-nerd",
    "tumbler",
    "typos",
    "typos-lsp-bin",
    "typst",
    "typstfmt-git",
    "unrar",
    "usbutils",
    "valgrind",
    "virt-manager",
    "vulkan-radeon",
    "wine-gecko",
    "wine-mono",
    "wine-staging",
    "winetricks",
    "xdg-desktop-portal-gtk",
    "zip",
    "zotero-bin",
    "zram-generator",
]
Cargo = [
    "bacon",
    "cargo-benchcmp",
    "cargo-binstall",
    "cargo-cache",
    "cargo-clone",
    "cargo-espflash",
    "cargo-generate",
    "cargo-heaptrack",
    "cargo-machete",
    "cargo-outdated",
    "cargo-release",
    "cargo-semver-checks",
    "cross",
    "espup",
    "handlr",
    "pacdef",
    "parse-changelog",
    "typos-cli",
]
Pipx = ["pass2csv"]
Rustup = [
    "1.78.0-x86_64-unknown-linux-gnu",
    "nightly-2023-10-13-x86_64-unknown-linux-gnu",
    "nightly-2024-01-04-x86_64-unknown-linux-gnu",
    "nightly-x86_64-unknown-linux-gnu",
    "stable-x86_64-unknown-linux-gnu",
]

