[arch]
dunst
waybar
ydotool
libnotify
playerctl
pavucontrol-qt
evremap-git
wl-clipboard
cliphist
hyprland
xdg-desktop-portal-hyprland
wf-recorder
grim
slurp
rofi-lbonn-wayland-git
pipewire
pipewire-audio
pipewire-alsa
pipewire-pulse
pipewire-jack
wireplumber
swaylock
swayidle
zenity
gnome-themes-extra
adwaita-qt5-git
adwaita-qt6-git
brightnessctl
