return {
	"Pocco81/auto-save.nvim",
	"tpope/vim-surround",
	'scrooloose/nerdcommenter',
	'tpope/vim-repeat',
	'romainl/vim-cool',
	'tpope/vim-eunuch',
	'sbdchd/neoformat',
	'gbprod/substitute.nvim',
	'svermeulen/vim-cutlass',
	'nvim-treesitter/nvim-treesitter',
 'hiphish/rainbow-delimiters.nvim',
 'rhysd/clever-f.vim',
 'tpope/vim-abolish',
 'ripytide/rust.vim',
 'mbbill/undotree',
 'kdheepak/lazygit.nvim',
}
