#! /bin/sh

#setup monitors
bspc monitor $MONITOR -d one two three four five six

#bspwm config
bspc config border_width 2
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true
bspc config pointer_follows_monitor true
bspc config window_gap 0
bspc config focused_border_color \#145DA0
bspc config active_border_color \#B1D4E0
bspc config normal_border_color \#000000

#bspwm rules
bspc rule -a Polybar state=floating
