[".config/bspwm/bspwmrc"]
monitor_config = """
bspc monitor HDMI3 -d 1 2 3 4 5 6
"""

[".config/rofi/config.rasi"]
monitor = """
	monitor: "HDMI3";
"""

[".config/dunst/dunstrc"]
monitor = """
	monitor = HDMI3
"""

["scripts/start.sh"]
keymapper = ""

[".config/polybar/config.ini"]
monitor = """
monitor = HDMI3
"""

[".config/fish/functions/toggle_polybar.fish"]
spacing_off = """
		bspc config -m HDMI3 top_padding 0
"""
spacing_on = """
		bspc config -m HDMI3 top_padding 20
"""
