[".config/bspwm/bspwmrc"]
monitor_config = """
bspc monitor eDP1 -d 1 2 3 4 5 6
"""

[".config/sxhkd/sxhkdrc"]
sht_keybinds = """
super + {s,h,t,g,y}
	fish -c "go_to_desktop {1,2,3,4,5}"

super + k
	fish -c "set -U DESKTOP_NUM 0"

super + l
	fish -c "set -U DESKTOP_NUM 3"
"""

[".config/rofi/config.rasi"]
monitor = """
	monitor: "eDP1";
"""
