[".config/bspwm/bspwmrc"]
monitor_config = """
bspc monitor eDP1 -d 1 2 3 4 5 6
"""

[".config/rofi/config.rasi"]
monitor = """
	monitor: "eDP1";
"""

[".config/dunst/dunstrc"]
monitor = """
	monitor = eDP1
"""

["scripts/start.sh"]
keymapper = """
key-mapper-control --command autoload &
"""

[".config/polybar/config.ini"]
monitor = """
monitor = eDP1
"""

[".config/fish/functions/toggle_polybar.fish"]
spacing_off = """
		bspc config -m eDP1 top_padding 0
"""
spacing_on = """
		bspc config -m eDP1 top_padding 20
"""
