[".config/bspwm/bspwmrc"]
monitor_config = """
bspc monitor eDP1 -d I II III IV V VI
"""

[".config/sxhkd/sxhkdrc"]
sht_keybinds = """
super + {s,h,t}
	bspc desktop -f ^{1,3,5}
"""

[".config/rofi/config.rasi"]
monitor = """
	monitor: "eDP1";
"""
