version: 4
serial:
  port: tcp://192.168.188.18:6638
  adapter: zstack
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost:1883
  client_id: z2m
frontend:
  enabled: true
  port: 1234
  host: 0.0.0.0
homeassistant:
  enabled: true
  legacy_action_sensor: true
devices:
  '0x7cc6b6fffe39eb33':
    friendly_name: Sonoff Button
  '0x0ceff6fffe59a108':
    friendly_name: Upstairs Climate
  '0x0ceff6fffe6a8d67':
    friendly_name: Downstairs Climate
  '0xa4c138d666b68f0e':
    friendly_name: '0xa4c138d666b68f0e'
