disabled_backends = ["rustup"]

arch_package_manager = "paru"

hostname_groups_enabled = true

[hostname_groups]
UKNML14830 = ["windows"]
sipper = ["arch_base", "gui", "laptop", "cargo", "hyprland"]
gamingpc = ["arch_base", "gui", "cargo", "hyprland", "plasma"]
archserver = ["arch_base"]
