device_name = "Dell KB216 Wired Keyboard"

[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTMETA"]
tap = ["KEY_ESC"]

[[remap]]
input = ["KEY_W"]
output = ["KEY_D"]
[[remap]]
input = ["KEY_E"]
output = ["KEY_R"]
[[remap]]
input = ["KEY_R"]
output = ["KEY_W"]
[[remap]]
input = ["KEY_T"]
output = ["KEY_B"]
[[remap]]
input = ["KEY_Y"]
output = ["KEY_J"]
[[remap]]
input = ["KEY_U"]
output = ["KEY_F"]
[[remap]]
input = ["KEY_I"]
output = ["KEY_U"]
[[remap]]
input = ["KEY_O"]
output = ["KEY_P"]
[[remap]]
input = ["KEY_P"]
output = ["KEY_SEMICOLON"]
[[remap]]
input = ["KEY_D"]
output = ["KEY_H"]
[[remap]]
input = ["KEY_F"]
output = ["KEY_T"]
[[remap]]
input = ["KEY_H"]
output = ["KEY_Y"]
[[remap]]
input = ["KEY_J"]
output = ["KEY_N"]
[[remap]]
input = ["KEY_K"]
output = ["KEY_E"]
[[remap]]
input = ["KEY_L"]
output = ["KEY_O"]
[[remap]]
input = ["KEY_SEMICOLON"]
output = ["KEY_I"]
[[remap]]
input = ["KEY_C"]
output = ["KEY_M"]
[[remap]]
input = ["KEY_V"]
output = ["KEY_C"]
[[remap]]
input = ["KEY_B"]
output = ["KEY_V"]
[[remap]]
input = ["KEY_N"]
output = ["KEY_K"]
[[remap]]
input = ["KEY_M"]
output = ["KEY_L"]

[[remap]]
input = ["KEY_DOT"]
output = ["KEY_COMMA"]
[[remap]]
input = ["KEY_SLASH"]
output = ["KEY_DOT"]

[[remap]]
input = ["KEY_LEFTSHIFT", "KEY_MINUS"]
output = ["KEY_LEFTSHIFT", "KEY_SLASH"]
[[remap]]
input = ["KEY_LEFTSHIFT", "KEY_8"]
output = ["KEY_SLASH"]

[[remap]]
input = ["KEY_LEFTSHIFT", "KEY_COMMA"]
output = ["KEY_LEFTSHIFT", "KEY_8"]
[[remap]]
input = ["KEY_COMMA"]
output = ["KEY_LEFTSHIFT", "KEY_MINUS"]
