#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-D-0 -d I II
bspc monitor DP-0 -d III IV
bspc monitor HDMI-0 -d V VI

bspc config border_width         2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config pointer_follows_monitor true
bspc config window_gap 0
bspc config focused_border_color \#145DA0
bspc config active_border_color \#B1D4E0
bspc config normal_border_color \#000000

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# turn off mouse acceleration
xinput --set-prop 14 303 0 1 &

# choose random wallpapers
/home/ripytide/wallpapers/scripts/changewallpaper 0 &
/home/ripytide/wallpapers/scripts/changewallpaper 2 &
/home/ripytide/wallpapers/scripts/changewallpaper 1 &

# enable playerctl daemon for media controls to work with the last active media source
playerctld daemon

# enable picom compositer for tranparency and blur
picom -b &

