#! /bin/sh

#restart sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#setup monitors
bspc monitor DVI-D-0 -d I II
bspc monitor DP-0 -d III IV
bspc monitor HDMI-0 -d V VI

#bspwm config
bspc config border_width         2
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config pointer_follows_monitor true
bspc config window_gap 0
bspc config focused_border_color \#145DA0
bspc config active_border_color \#B1D4E0
bspc config normal_border_color \#000000

#bspwm rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Polybar state=floating

./home/ripytide/scripts/start.sh
