packages = ["main"]

[variables]
workmode = true
personalmode = false

[files]
"./home/.config" = "~/AppData/Local"
"./home/.config/powershell" = "~/OneDrive - Renishaw plc/Documents/PowerShell/"
"./home/.config/windowsterminal" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
"./home/.config/komorebi" = "~"
"./home/.config/kanata" = "~"
"./home/.config/whkdrc" = "~/whkdrc"
"./home/.gitconfig" = "~/.gitconfig"
"./home/.config/nushell" = "~/AppData/Roaming/nushell"

"./root/coding" = "C:/coding"
