packages = ["main"]

[variables]
workmode = true
personalmode = false

[files]
"home/.config" = "~/AppData/Local"
"home/.config/metapac" = "~/AppData/Roaming/metapac"
"home/.config/nushell" = "~/AppData/Roaming/nushell"
"home/.config/lazygit" = { target = "~/AppData/Local/lazygit", type = "symbolic" }
"home/.config/powershell" = "~/OneDrive - Renishaw plc/Documents/PowerShell"
"home/.config/windowsterminal" = "~/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState"
"home/.config/komorebi" = "~"
"home/.config/kanata" = "~"
"home/.config/whkdrc" = "~/.config/whkdrc"
"home/.gitconfig" = "~/.gitconfig"
"root/coding" = "C:/coding"
