arch = [
	# base
	"arch-install-scripts",
	"dnsmasq",
	"linux",
	"linux-firmware",
	"efibootmgr",
	"base",
	"base-devel",
	"gcc",
	"clang",
	"compiler-rt",
	"git",
	"rustup",
	"python",
	"gcr",
	"man-db",
	"networkmanager",
	"inetutils",
	"net-tools",
	"openssl-1.1",
	"usbutils",
	"zram-generator",
	"cifs-utils",
	"ffmpeg",
	"avahi",
	"ntfs-3g",

	# package/dotfile management
	"reflector",
	"paru-bin",
	"metapac",
	"dotter-rs-bin",
	"downgrade",

	# services
	{ package = "syncthing", hooks = { after_install = [
		"sudo",
		"systemctl",
		"enable",
		"--now",
		"syncthing@ripytide",
	] } },

	# cli
	"skim",
	"nmap",
	"fd",
	"gpg-tui",
	"yazi",
	"dua-cli",
	"ncdu",
	"rsync",
	"arp-scan",
	"dog",
	"unzip",
	"eza",
	"fzf",
	"bat",
	"sd",
	"sxiv",
	"git-delta",
	"bottom",
	"neovim-nightly-bin",
	# required for image viewing in neovim
	"imagemagick",
	"zoxide",
	"lazygit",
	"ripgrep",
	"tealdeer",
	"less",
	"parallel",
	"7zip",
	"unrar",
	"zip",
	"fastfetch",
	"jq",
	"trippy",
	"git-cliff",
	"restic",

	# shell
	"nushell",
	"starship",
	"krabby-bin",

	# docker
	"docker",
	"docker-compose",

	# generic drivers
	"libva-utils",
	"vulkan-tools",
	"vulkan-icd-loader",
	"mesa",

	# amd drivers
	"amd-ucode",
	"vulkan-radeon",

	# intel drivers
	"intel-ucode",
	"vulkan-intel",

	# nvidia drivers
	"nvidia-dkms",
	"nvidia-utils",
	"nvidia-settings",
]

cargo = ["rip2"]
