cargo = [
	"bacon",
	"cargo-benchcmp",
	"cargo-binstall",
	"cargo-clone",
	"cargo-machete",
	"cargo-outdated",
	"cargo-release",
	"cargo-semver-checks",
	"cargo-aur",
	"cargo-dist",
	"cargo-update",
	"cargo-udeps",
	"kanata",
]
