arch = [
    "gamescope",
    "lib32-mangohud",
    "lutris",
    "mangohud",

	# lib32 drivers
	"lib32-mesa",
	"lib32-vulkan-icd-loader",
	"lib32-vulkan-radeon",
	"lib32-vulkan-intel",
	"lib32-nvidia-utils",
]
