arch = [
	# wayland
	"ydotool",
	"libnotify",
	"playerctl",
	"pavucontrol-qt",
	"wl-clipboard",
	"cliphist",
	"wf-recorder",
	"grim",
	"slurp",
	"rofi-lbonn-wayland-git",
	"pipewire",
	"pipewire-audio",
	"pipewire-alsa",
	"pipewire-pulse",
	"pipewire-jack",
	"wireplumber",
	"gnome-themes-extra",
	"adwaita-qt5-git",
	"adwaita-qt6-git",
	"brightnessctl",

	# core apps
	"kitty",
	"zen-browser-bin",
	"bitwarden",
	"chromium",
	"network-manager-applet",

	# extra apps
	"gnome-characters",
	"discord",
	"gparted",
	"gucharmap",
	"qbittorrent",
	"obsidian",
	"pdfarranger",
	"hunspell-en_gb",
	"libreoffice-fresh",
	"kicad",
	"freecad",
	"inkscape",
	"calibre",
	"vlc",
	"gimp",
	"code",
	"kooha",
	"krita",
	"mullvad-vpn-bin",
    "rustdesk-bin",
]
