arch = [
	# base
	"arch-install-scripts",
	"dnsmasq",
	"linux",
	"linux-firmware",
	"base",
	"base-devel",
	"gcc",
	"git",
	"rustup",
	"python",
	"gcr",
	"man-db",
	"networkmanager",
	"inetutils",
	"net-tools",
	"openssl-1.1",
	"usbutils",
	"zram-generator",

	# package/dotfile management
	"reflector",
	"paru-bin",
	"metapac-bin",
	"dotter-rs-bin",
	"downgrade",

	# fonts
	"noto-fonts",
	"noto-fonts-emoji",
	"ttf-fira-code",
	"ttf-firacode-nerd",
	"ttf-nerd-fonts-symbols",
	"ttf-font-awesome",
	"nerd-fonts",

	# dev
	"rust-analyzer",
	"gnuplot",
	"mosquitto",
	"npm",
	"opencv",
	"python-opencv",
	"tokei",
	"python-black",
	"clang",

	# laptop
	"bluetuith-bin",
	"acpi",
	"batsignal",

	# wayland
	"dunst",
	"waybar",
	"ydotool",
	"libnotify",
	"playerctl",
	"pavucontrol-qt",
	"wl-clipboard",
	"cliphist",
	"hyprland",
	"xdg-desktop-portal-hyprland",
	"wf-recorder",
	"grim",
	"slurp",
	"rofi-lbonn-wayland-git",
	"pipewire",
	"pipewire-audio",
	"pipewire-alsa",
	"pipewire-pulse",
	"pipewire-jack",
	"wireplumber",
	"swaylock",
	"swayidle",
	"zenity",
	"gnome-themes-extra",
	"adwaita-qt5-git",
	"adwaita-qt6-git",
	"brightnessctl",

	# core apps
	"kitty",
	"firefox",
	"bitwarden",
	"chromium",
	"network-manager-applet",

	# extra apps
	"gnome-characters",
	"discord",
	"gparted",
	"gucharmap",
	"qbittorrent",
	"obsidian",
	"pdfarranger",
	"hunspell-en_gb",
	"libreoffice-fresh",
	"kicad",
	"freecad",
	"inkscape",
	"calibre",
	"syncthing",
	"vlc",
	"gimp",
	"code",
	"kooha",
	"krita",
	"mullvad-vpn-bin",

	# cli
	"fd",
	"yazi",
	"dua-cli",
	"rsync",
	"arp-scan",
	"dog",
	"unzip",
	"eza",
	"fzf",
	"bat",
	"sd",
	"sxiv",
	"git-delta",
	"bottom",
	"neovim",
	"zoxide",
	"lazygit",
	"ripgrep",
	"tealdeer",
	"rm-improved",
	"pass",
	"less",
	"parallel",
	"p7zip",
	"unrar",
	"zip",
	"unzip",
	"fastfetch",
	"jq",
	"trippy",
	"git-cliff",

	# file explorer
	"thunar",
	"thunar-archive-plugin",
	"thunar-media-tags-plugin",
	"thunar-volman",
	"ffmpegthumbnailer",
	"gvfs",
	"gvfs-smb",
	"tumbler",

	# lsp
	"typos",
	"typos-lsp-bin",

	# shell
	"nushell",
	"starship",
	"krabby-bin",

	# docker
	"docker",
	"docker-compose",

	# formatters
	"lua-format",
	"mdformat",
	"shfmt",

	# amd
	"amd-ucode",
	"amdvlk",
	"mesa",
	"vulkan-radeon",

	# intel
	"intel-ucode",
	"vulkan-intel",
]

cargo = [
	"bacon",
	"cargo-benchcmp",
	"cargo-binstall",
	"cargo-clone",
	"cargo-machete",
	"cargo-outdated",
	"cargo-release",
	"cargo-semver-checks",
	"cargo-aur",
	"cargo-dist",
	"cargo-update",
	"cargo-udeps",
	{ package = "kanata", version = "1.7.0-prerelease-2" },
]
