cargo = [
	# "skim",
    "cargo-binstall",
    "bat",
    "bottom",
    "difftastic",
    "dotter",
    "eza",
    "fd-find",
    "git-delta",
    # "komorebi",
    # "komorebi-bar",
    # "komorebi-gui",
    # "komorebic",
    # "komorebic-no-console",
    "krabby",
    "nu",
    "onefetch",
    "rip2",
    "ripgrep",
    "sd",
    "starship",
    "suckit",
    "tealdeer",
    "tokei",
    "whkd",
    "zoxide",
	"metapac",
	"kanata",
]

winget = [
	"7zip.7zip",
	"DEVCOM.Lua",
	"Git.Git",
	"JesseDuffield.lazygit",
	"Kitware.CMake",
	"LLVM.LLVM",
	"Microsoft.AppInstaller",
	"Microsoft.CLRTypesSQLServer.2019",
	"Microsoft.DevHome",
	"Microsoft.DotNet.DesktopRuntime.6",
	"Microsoft.DotNet.DesktopRuntime.8",
	"Microsoft.Edge",
	"Microsoft.EdgeWebView2Runtime",
	"Microsoft.Office",
	"Microsoft.OneDrive",
	"Microsoft.PowerShell",
	"Microsoft.Teams",
	"Microsoft.UI.Xaml.2.7",
	"Microsoft.UI.Xaml.2.8",
	"Microsoft.VCLibs.Desktop.14",
	"Microsoft.VCRedist.2005.x86",
	"Microsoft.VCRedist.2008.x86",
	"Microsoft.VCRedist.2010.x64",
	"Microsoft.VCRedist.2010.x86",
	"Microsoft.VCRedist.2015+.x64",
	"Microsoft.VCRedist.2015+.x86",
	"Microsoft.VSTOR",
	"Microsoft.VisualStudio.2019.Professional",
	"Microsoft.VisualStudio.2022.Professional",
	"Microsoft.WinDbg",
	"Microsoft.WindowsSDK.10.0.19041",
	"Microsoft.WindowsTerminal",
	"Microsoft.msodbcsql.17",
	"Zen-Team.Zen-Browser",
	"NSIS.NSIS",
	"Neovim.Neovim",
	"Notepad++.Notepad++",
	"OpenJS.NodeJS",
	"Python.Launcher",
	"Python.Python.3.12",
	"Rustlang.Rustup",
	"WiXToolset.WiXToolset",
	"junegunn.fzf",
	"Ablaze.Floorp"
]
