cargo = [
    "cargo-binstall",
    "bat",
    "bottom",
    "difftastic",
    "dog",
    "dotter",
    "eza",
    "fd-find",
    "git-delta",
    "komorebi",
    "komorebi-bar",
    "komorebi-gui",
    "komorebic",
    "komorebic-no-console",
    "krabby",
    "lf",
    "nu",
    "onefetch",
    "rip2",
    "ripgrep",
    "sd",
    "starship",
    "suckit",
    "tealdeer",
    "tokei",
    "whkd",
    "zoxide",
	"metapac",
	{ package = "kanata", version = "1.7.0-prerelease-2" },
]

winget = [
	"7zip.7zip",
	"Adobe.Acrobat.Reader.32-bit",
	"DEVCOM.Lua",
	"Flameshot.Flameshot",
	"Flow-Launcher.Flow-Launcher",
	"Git.Git",
	"GitExtensionsTeam.GitExtensions",
	"JanDeDobbeleer.OhMyPosh",
	"JesseDuffield.lazygit",
	"KDE.KDiff3",
	"Kitware.CMake",
	"LLVM.LLVM",
	"Microsoft.AppInstaller",
	"Microsoft.CLRTypesSQLServer.2019",
	"Microsoft.DevHome",
	"Microsoft.DotNet.DesktopRuntime.6",
	"Microsoft.DotNet.DesktopRuntime.8",
	"Microsoft.Edge",
	"Microsoft.EdgeWebView2Runtime",
	"Microsoft.Office",
	"Microsoft.OneDrive",
	"Microsoft.PowerShell",
	"Microsoft.Teams",
	"Microsoft.UI.Xaml.2.7",
	"Microsoft.UI.Xaml.2.8",
	"Microsoft.VCLibs.Desktop.14",
	"Microsoft.VCRedist.2005.x86",
	"Microsoft.VCRedist.2008.x86",
	"Microsoft.VCRedist.2010.x64",
	"Microsoft.VCRedist.2010.x86",
	"Microsoft.VCRedist.2015+.x64",
	"Microsoft.VCRedist.2015+.x86",
	"Microsoft.VSTOR",
	"Microsoft.VisualStudio.2019.Professional",
	"Microsoft.VisualStudio.2022.Professional",
	"Microsoft.WinDbg",
	"Microsoft.WindowsSDK.10.0.19041",
	"Microsoft.WindowsTerminal",
	"Microsoft.msodbcsql.17",
	"Mozilla.Firefox",
	"NSIS.NSIS",
	"Neovim.Neovim",
	"Notepad++.Notepad++",
	"OpenJS.NodeJS",
	"Python.Launcher",
	"Python.Python.3.12",
	"Rustlang.Rustup",
	"WiXToolset.WiXToolset",
	"WinMerge.WinMerge",
	"gerardog.gsudo",
	"junegunn.fzf",
	"Ablaze.Floorp"
]
